# permissions for end users to edit bucketaccesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bucketaccess-editor-role
rules:
- apiGroups:
  - sigs.k8s.io.my.domain
  resources:
  - bucketaccesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sigs.k8s.io.my.domain
  resources:
  - bucketaccesses/status
  verbs:
  - get
