# permissions for end users to view bucketclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bucketclass-viewer-role
rules:
- apiGroups:
  - sigs.k8s.io.my.domain
  resources:
  - bucketclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sigs.k8s.io.my.domain
  resources:
  - bucketclasses/status
  verbs:
  - get
