# permissions for end users to edit bucketaccessrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bucketaccessrequest-editor-role
rules:
- apiGroups:
  - sigs.k8s.io.my.domain
  resources:
  - bucketaccessrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sigs.k8s.io.my.domain
  resources:
  - bucketaccessrequests/status
  verbs:
  - get
