# permissions for end users to edit bucketcontents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bucketcontent-editor-role
rules:
- apiGroups:
  - sigs.k8s.io.my.domain
  resources:
  - bucketcontents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sigs.k8s.io.my.domain
  resources:
  - bucketcontents/status
  verbs:
  - get
